name: Build and deploy on prod

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - v1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout sources

      - uses: ruby/setup-ruby@v1
        name: Set up Ruby
        with:
          ruby-version: "2.7.7"

      - run: make upgrade install
        name: Set up build dependencies

      - run: make build
        name: Build sources

      - uses: actions/upload-artifact@v3
        name: Persist artifact
        with:
          name: aca-workshop
          path: _site

      - uses: azure/CLI@v1
        name: Deploy
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
        with:
          azcliversion: 2.44.1
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt

            az storage azcopy blob upload \
              --container "\$web" \
              --destination "${GITHUB_REF##*/}" \
              --recursive \
              --source "_site/*"
