on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - uses: azure/CLI@v1
        name: Delete the website of the feature branch
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
        with:
          azcliversion: 2.44.1
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt

            BRANCH=${{ github.event.pull_request.head.ref }}
            BRANCH=${BRANCH#refs/*/}
            BRANCH=${BRANCH//\//-}

            az storage azcopy blob delete \
              --container "\$web" \
              --target "${BRANCH}" \
              --recursive
