name: Clean logs
run-name: Clean runs logs older than a week

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 1' # every Monday

jobs:
 Cleaning:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: igorjs/gh-actions-clean-workflow@v3.0.1
        with:
          days_old: 14 
          token: ${{ github.token }}
      - uses: gautamkrishnar/keepalive-workflow@v1
